version: "3"
services:

  postgres:
    build: ./database
    container_name: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  go-api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres
    command: air

  react-app:
    container_name: react
    build: ./fontend
    volumes:
      - ./fontend/src:/app/src
      - ./fontend/public/assets:/app/public/assets
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start